spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: pallet-sorting-api

application:
  storage:
    base-path: ${STORAGE_PATH:./uploads}
    allowed-extensions: pdf,jpg,jpeg,png,doc,docx,xml
    max-file-size: 10485760  # 10MB in bytes
  onesignal:
    app-id: ${ONESIGNAL_APP_ID}
    rest-api-key: ${ONESIGNAL_REST_API_KEY}
  cloudflare:
    r2:
      account-id: ${CF_R2_ACCOUNT_ID:}
      access-key-id: ${CF_R2_ACCESS_KEY_ID:}
      secret-access-key: ${CF_R2_SECRET_ACCESS_KEY:}
      bucket-name: ${CF_R2_BUCKET_NAME:tupack-docs}
      public-url: ${CF_R2_PUBLIC_URL:}
  company:
    ruc: ${COMPANY_RUC:20613601296}
