spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: ${SERVER_PORT:8080}

application:
  security:
    jwt:
      secret: ${JWT_SECRET}
      access-token-expiration-minutes: ${JWT_EXPIRATION:30}
      refresh-token-expiration-days: ${REFRESH_TOKEN_DAYS:7}
    permit-all: false
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    com.tupack.palletsortingapi: INFO
